import {api,APIError} from './api.js';
import {icon,escapeHTML,initials,setTimeZone} from './ui.js';
import {navItems,pageMeta,renderAdminPage,openCreateBooking} from './admin.js';
import {renderPublicApp} from './public.js';

const root=document.querySelector('#app');
const state={user:null,organization:null,locations:[],page:'dashboard',pending:0};
if(location.pathname.startsWith('/book')) renderPublicApp(root).catch(showFatal); else boot();

async function boot(){root.innerHTML='<div class="boot"><span></span><p>Загружаем рабочее пространство…</p></div>';try{const me=await api.me();Object.assign(state,me);setTimeZone(me.locations?.[0]?.timezone||me.organization.timezone);mount()}catch(e){showLogin(e.status===401?'':e.message)}}
function showFatal(e){root.innerHTML=`<main class="fatal"><div>${icon('warning')}<h1>Сервис временно недоступен</h1><p>${escapeHTML(e.message)}</p></div></main>`}
function showLogin(message=''){root.innerHTML=`<main class="login"><section class="login-art"><div class="login-brand"><b>B</b>Booking OS</div><div><small>RESOURCE-FIRST BOOKING</small><h1>Брони без хаоса.<br><em>Ресурсы без конфликтов.</em></h1><p>Заявки из WhatsApp, 2GIS, Instagram, телефона и сайта — в одном живом календаре.</p></div><div class="login-stats"><span><b>1 окно</b>для всех каналов</span><span><b>0 дублей</b>атомарная бронь</span><span><b>24/7</b>онлайн-запись</span></div></section><section class="login-form-wrap"><form id="login-form" class="login-card"><small>ДОБРО ПОЖАЛОВАТЬ</small><h2>Войдите в пространство</h2><p>Управляйте заявками, загрузкой и оплатами.</p><label>Email<input name="email" type="email" value="owner@booking.local" required></label><label>Пароль<input name="password" type="password" value="demo1234" required></label><div class="form-error" ${message?'':'hidden'}>${escapeHTML(message)}</div><button class="btn primary" type="submit">Войти ${icon('arrow')}</button><aside><b>Демо-доступ</b><br>owner@booking.local · demo1234</aside></form></section></main>`;root.querySelector('form').onsubmit=async e=>{e.preventDefault();const b=e.currentTarget.querySelector('button'),d=new FormData(e.currentTarget),err=e.currentTarget.querySelector('.form-error');b.disabled=true;b.textContent='Входим…';err.hidden=true;try{await api.login(d.get('email'),d.get('password'));await boot()}catch(x){err.textContent=x.message;err.hidden=false;b.disabled=false;b.innerHTML=`Войти ${icon('arrow')}`}}}
function mount(){root.innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand"><b>B</b><span>Booking OS<small>BUSINESS WORKSPACE</small></span></div><div class="workspace"><i>${escapeHTML(initials(state.organization.name))}</i><span><b>${escapeHTML(state.organization.name)}</b><small>${escapeHTML(state.locations?.[0]?.name||'Основная точка')}</small></span>${icon('down')}</div><nav>${navItems.map(n=>`<button data-nav="${n.id}" class="${n.id===state.page?'active':''}">${icon(n.icon)}<span>${n.label}</span>${n.badge?'<i class="nav-badge" hidden></i>':''}</button>`).join('')}</nav><div class="sidebar-bottom"><button data-public>${icon('external')}<span>Онлайн-запись<small>Открыть страницу клиента</small></span></button><div class="profile"><i>${escapeHTML(initials(state.user.name))}</i><span><b>${escapeHTML(state.user.name)}</b><small>${escapeHTML(state.user.role)}</small></span><button id="logout">${icon('logout')}</button></div></div></aside><section class="work"><header class="topbar"><button id="menu" class="icon-btn">${icon('menu')}</button><div><small id="crumb">${pageMeta[state.page][1]}</small><b id="top-title">${pageMeta[state.page][0]}</b></div><div class="top-actions"><button class="icon-btn">${icon('search')}</button><button class="btn primary" id="global-new">${icon('plus')} Новая бронь</button></div></header><div id="page"></div></section></div>`;bindShell();navigate(state.page)}
function bindShell(){root.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>navigate(b.dataset.nav));root.querySelectorAll('[data-public]').forEach(b=>b.onclick=()=>window.open('/book','_blank'));root.querySelector('#global-new').onclick=()=>openCreateBooking(ctx());root.querySelector('#logout').onclick=async()=>{await api.logout();showLogin()};root.querySelector('#menu').onclick=()=>root.querySelector('.sidebar').classList.toggle('open')}
function ctx(){return{state,navigate,refresh:()=>navigate(state.page),setPending:n=>{state.pending=n;const b=root.querySelector('.nav-badge');if(b){b.hidden=!n;b.textContent=n}},openCreate:()=>openCreateBooking(ctx())}}
async function navigate(page){state.page=page;root.querySelectorAll('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===page));root.querySelector('.sidebar')?.classList.remove('open');const m=pageMeta[page]||pageMeta.dashboard;root.querySelector('#crumb').textContent=m[1];root.querySelector('#top-title').textContent=m[0];const p=root.querySelector('#page');p.innerHTML='<div class="page-loading"><span></span><span></span><span></span></div>';await renderAdminPage(page,p,ctx())}
